[build]
  command = "npm run build"```publish = "dist"```environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/```ex.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' ```safe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data```ttps:; font-src 'self' data:; connect-src 'self' https:; frame-src 'none'```    X-Frame-Options = "```Y"
    X-Content-Type-Options = "nosn```"
    X-XSS-Protection = "```mode=block"
    Referrer-Policy = "strict```igin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/```ets/*"
  [headers.values]
    Cache-Control = "```lic, max-age=31536000, immutable"

[[headers]]
  for = "*.```"
  [headers.values]
    Cache-Control = "```lic, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
